# Use root/secret as user/password credentials
version: '3.1'
EEEEEEEEEEEEEEE
services:

  mongo:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret 

networks:
    mongo-network:
    
volumes:
    mongo-data:
